/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_tasks__task_id__patch"];
        trace?: never;
    };
    "/tasks/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Update Tasks */
        post: operations["bulk_update_tasks_tasks_bulk_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description Newest first. How a client finds today's 09:00 / 17:00 review.
         */
        get: operations["list_reviews_approval_requests_get"];
        put?: never;
        /**
         * Create Manual Review
         * @description Start a MANUAL review now, outside the 09:00 / 17:00 schedule. Sends
         *     nothing by itself -- it still has to be approved through ``/commit``.
         */
        post: operations["create_manual_review_approval_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_approval_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{request_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Review */
        post: operations["open_review_approval_requests__request_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Review */
        post: operations["cancel_review_approval_requests__request_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{request_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Review
         * @description Render without approving -- a pure function of current data, safe to
         *     call repeatedly as the user toggles recipients before committing.
         */
        post: operations["preview_review_approval_requests__request_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{request_id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Image
         * @description The table image a commit right now would freeze. 404 in text format.
         */
        get: operations["preview_image_approval_requests__request_id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{request_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Review */
        post: operations["commit_review_approval_requests__request_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatsapp/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_whatsapp_groups_get"];
        put?: never;
        /**
         * Add Group
         * @description Pins the JID the caller supplies -- normally one just returned by
         *     ``/whatsapp/groups/resolve`` -- permanently. It is never re-resolved by
         *     name at send time, so a later rename or a second similarly-named group
         *     cannot silently redirect a report.
         */
        post: operations["add_group_whatsapp_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatsapp/groups/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Group */
        post: operations["resolve_group_whatsapp_groups_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatsapp/groups/{group_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Group Enabled */
        patch: operations["set_group_enabled_whatsapp_groups__group_id__enabled_patch"];
        trace?: never;
    };
    "/whatsapp/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whatsapp Status */
        get: operations["whatsapp_status_whatsapp_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/recipients/{recipient_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Recipient */
        post: operations["retry_recipient_shares_recipients__recipient_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/snapshots/{snapshot_id}/image.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot Image
         * @description The exact image that was approved and sent. Immutable, so cacheable.
         */
        get: operations["snapshot_image_shares_snapshots__snapshot_id__image_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conflicts */
        get: operations["list_conflicts_sync_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/conflicts/{conflict_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Conflict */
        post: operations["resolve_conflict_sync_conflicts__conflict_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ui Config */
        get: operations["ui_config_config_ui_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovalKind
         * @enum {string}
         */
        ApprovalKind: "MORNING" | "EVENING" | "MANUAL";
        /** ApprovalRequestOut */
        ApprovalRequestOut: {
            /** Id */
            id: string;
            /** Display Id */
            display_id: string;
            kind: components["schemas"]["ApprovalKind"];
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            state: components["schemas"]["ApprovalState"];
            /** Opened At */
            opened_at: string | null;
            /** Approved By User Id */
            approved_by_user_id: string | null;
            /** Approved At */
            approved_at: string | null;
        };
        /**
         * ApprovalState
         * @description One scheduled review. Ends when the user decides what to do with it.
         * @enum {string}
         */
        ApprovalState: "DRAFT" | "REVIEW_PENDING" | "USER_EDITING" | "READY" | "APPROVED" | "CLOSED_NO_SHARE" | "CANCELLED" | "EXPIRED";
        /** BulkUpdateItemRequest */
        BulkUpdateItemRequest: {
            /** Task Id */
            task_id: string;
            changes: components["schemas"]["TaskEditFields"];
            /** Expected Version */
            expected_version: number;
        };
        /** BulkUpdateRequest */
        BulkUpdateRequest: {
            /** Items */
            items: components["schemas"]["BulkUpdateItemRequest"][];
        };
        /** ChangeSummaryOut */
        ChangeSummaryOut: {
            /** Added */
            added: number;
            /** Completed */
            completed: number;
            /** Modified */
            modified: number;
            /** Overdue */
            overdue: number;
            /** Still Pending */
            still_pending: number;
        };
        /**
         * CommitMode
         * @enum {string}
         */
        CommitMode: "UPDATE_ONLY" | "UPDATE_AND_SHARE" | "SHARE_ONLY";
        /** CommitRequest */
        CommitRequest: {
            mode: components["schemas"]["CommitMode"];
            /** Action Version */
            action_version: number;
            /** Task Updates */
            task_updates?: components["schemas"]["CommitTaskUpdate"][];
            /** Recipient Group Ids */
            recipient_group_ids?: string[];
            /** Send At */
            send_at?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Template Source */
            template_source?: string | null;
            /** Expected Content Hash */
            expected_content_hash?: string | null;
        };
        /** CommitResponse */
        CommitResponse: {
            /** Request Id */
            request_id: string;
            mode: components["schemas"]["CommitMode"];
            job: components["schemas"]["ShareJobOut"] | null;
            /** Recipients */
            recipients: components["schemas"]["ShareRecipientOut"][];
            /** Preview */
            preview: string | null;
            /** Already Committed */
            already_committed: boolean;
        };
        /** CommitTaskUpdate */
        CommitTaskUpdate: {
            /** Task Id */
            task_id: string;
            changes: components["schemas"]["TaskEditFields"];
            /** Expected Version */
            expected_version: number;
        };
        /**
         * ConflictResolution
         * @description A human's decision on a parked collision. Shared by the service layer,
         *     the API schema, and the database CHECK constraint (``models/sync.py``'s
         *     ``RESOLUTIONS``) so the three cannot drift to accept different values.
         * @enum {string}
         */
        ConflictResolution: "kept_db" | "kept_sheet";
        /** GroupCandidateOut */
        GroupCandidateOut: {
            /** External Jid */
            external_jid: string;
            /** Display Name */
            display_name: string;
            /** Member Count */
            member_count: number | null;
            /** Confidence */
            confidence: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Rendered Body */
            rendered_body: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Has Image
             * @default false
             */
            has_image: boolean;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        /**
         * RecipientState
         * @description One group, one job. The actual unit of delivery.
         * @enum {string}
         */
        RecipientState: "QUEUED" | "SENDING" | "SENT" | "FAILED" | "SKIPPED" | "CANCELLED";
        /** ResolveConflictRequest */
        ResolveConflictRequest: {
            resolution: components["schemas"]["ConflictResolution"];
        };
        /** ResolveGroupRequest */
        ResolveGroupRequest: {
            /** Name */
            name: string;
        };
        /** ReviewDetailOut */
        ReviewDetailOut: {
            request: components["schemas"]["ApprovalRequestOut"];
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
            summary: components["schemas"]["TaskSummaryOut"];
            changes_since_last_share: components["schemas"]["ChangeSummaryOut"];
            /** Shares */
            shares?: components["schemas"]["ShareOut"][];
        };
        /** ShareJobOut */
        ShareJobOut: {
            /** Id */
            id: string;
            /** Display Id */
            display_id: string;
            state: components["schemas"]["ShareJobState"];
            /** Action Version */
            action_version: number;
            /** Deferred Reason */
            deferred_reason: string | null;
            /** Sent At */
            sent_at: string | null;
        };
        /**
         * ShareJobState
         * @description One approved send. Fans out to one or more recipients.
         * @enum {string}
         */
        ShareJobState: "PENDING" | "SCHEDULED" | "RESCHEDULED" | "DEFERRED" | "SENDING" | "SENT" | "PARTIALLY_SENT" | "FAILED" | "CANCELLED" | "SUPERSEDED";
        /**
         * ShareOut
         * @description One approved send and how it went, per group -- the review screen's
         *     delivery panel.
         */
        ShareOut: {
            job: components["schemas"]["ShareJobOut"];
            /** Run At */
            run_at: string | null;
            /** Rendered Body */
            rendered_body: string;
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * Has Image
             * @default false
             */
            has_image: boolean;
            /** Recipients */
            recipients: components["schemas"]["ShareRecipientOut"][];
        };
        /** ShareRecipientOut */
        ShareRecipientOut: {
            /** Id */
            id: string;
            /** Whatsapp Group Id */
            whatsapp_group_id: string;
            state: components["schemas"]["RecipientState"];
            /** Attempts */
            attempts: number;
            /** Client Message Id */
            client_message_id: string;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string;
        };
        /** SyncConflictOut */
        SyncConflictOut: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Db Value */
            db_value: {
                [key: string]: unknown;
            };
            /** External Value */
            external_value: {
                [key: string]: unknown;
            } | null;
            /** Resolution */
            resolution: string | null;
            /** Resolved By */
            resolved_by: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Is Open */
            is_open: boolean;
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Project Id */
            project_id?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** @default MEDIUM */
            priority: components["schemas"]["Priority"];
            /** @default PENDING */
            status: components["schemas"]["TaskStatus"];
            /** Due Date */
            due_date?: string | null;
            /**
             * Remarks
             * @default
             */
            remarks: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /**
         * TaskEditFields
         * @description Every field PATCH /tasks/{id} may change. All optional -- only fields
         *     actually present in the request body are applied, via
         *     ``model_dump(exclude_unset=True)``, so "not sent" and "explicitly set to
         *     its current value" are properly distinguishable from "clear this field".
         */
        TaskEditFields: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            priority?: components["schemas"]["Priority"] | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Due Date */
            due_date?: string | null;
            /** Remarks */
            remarks?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: string;
            /** Display Id */
            display_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Project Id */
            project_id: string | null;
            /** Owner Id */
            owner_id: string | null;
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["TaskStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Remarks */
            remarks: string;
            /** Tags */
            tags: string[];
            source: components["schemas"]["TaskSourceKind"];
            /** Version */
            version: number;
            /** Last Shared At */
            last_shared_at: string | null;
        };
        /**
         * TaskSourceKind
         * @description Where a task last came from. Used for audit, not for routing.
         * @enum {string}
         */
        TaskSourceKind: "APP" | "GOOGLE_SHEETS" | "EXCEL" | "IMPORT" | "SHEET_IMPORT";
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "BLOCKED" | "DEFERRED";
        /** TaskSummaryOut */
        TaskSummaryOut: {
            /** Completed */
            completed: number;
            /** Pending */
            pending: number;
            /** In Progress */
            in_progress: number;
            /** Blocked */
            blocked: number;
            /** Deferred */
            deferred: number;
            /** Overdue */
            overdue: number;
            /** Due Today */
            due_today: number;
            /** Newly Added */
            newly_added: number;
            /** Modified Today */
            modified_today: number;
            /** Completed Today */
            completed_today: number;
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
        };
        /**
         * UiConfigOut
         * @description The few settings the browser UI needs to label things correctly.
         */
        UiConfigOut: {
            /** Timezone */
            timezone: string;
            /**
             * Morning Alert Time
             * Format: time
             */
            morning_alert_time: string;
            /**
             * Evening Alert Time
             * Format: time
             */
            evening_alert_time: string;
            /** Allow Custom Send Time */
            allow_custom_send_time: boolean;
            /** Sheet Url */
            sheet_url: string | null;
            /** User Name */
            user_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhatsAppGroupCreateRequest */
        WhatsAppGroupCreateRequest: {
            /** Display Name */
            display_name: string;
            /** External Jid */
            external_jid: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Default Morning
             * @default false
             */
            default_morning: boolean;
            /**
             * Default Evening
             * @default false
             */
            default_evening: boolean;
        };
        /** WhatsAppGroupOut */
        WhatsAppGroupOut: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** External Jid */
            external_jid: string;
            /** Enabled */
            enabled: boolean;
            /** Description */
            description: string;
            /** Default Morning */
            default_morning: boolean;
            /** Default Evening */
            default_evening: boolean;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** WhatsAppStatusOut */
        WhatsAppStatusOut: {
            /** Provider */
            provider: string;
            /** State */
            state: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Last Successful Send At */
            last_successful_send_at: string | null;
            /** Can Send */
            can_send: boolean;
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_tasks_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"][] | null;
                priority?: components["schemas"]["Priority"][] | null;
                owner_id?: string | null;
                project_id?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskEditFields"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_tasks_tasks_bulk_update_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_approval_requests_get: {
        parameters: {
            query?: {
                local_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_review_approval_requests_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_approval_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_review_approval_requests__request_id__open_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_review_approval_requests__request_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_review_approval_requests__request_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_image_approval_requests__request_id__preview_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_review_approval_requests__request_id__commit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_whatsapp_groups_get: {
        parameters: {
            query?: {
                enabled_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppGroupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_group_whatsapp_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatsAppGroupCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_group_whatsapp_groups_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_group_enabled_whatsapp_groups__group_id__enabled_patch: {
        parameters: {
            query: {
                enabled: boolean;
            };
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_status_whatsapp_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppStatusOut"];
                };
            };
        };
    };
    retry_recipient_shares_recipients__recipient_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareRecipientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_image_shares_snapshots__snapshot_id__image_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conflicts_sync_conflicts_get: {
        parameters: {
            query?: {
                open_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncConflictOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_conflict_sync_conflicts__conflict_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string | null;
                "x-actor-name"?: string | null;
            };
            path: {
                conflict_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveConflictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncConflictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ui_config_config_ui_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiConfigOut"];
                };
            };
        };
    };
}
