"""initial schema

Revision ID: bdffd15a31c5
Revises: 
Create Date: 2026-09-16 14:09:01.783141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdffd15a31c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('actor_kind', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=26), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=26), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("actor_kind IN ('USER', 'SYSTEM', 'SYNC', 'AGENT')", name='ck_audit_actor_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash'),
    sa.UniqueConstraint('seq')
    )
    op.create_index('idx_audit_correlation', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('IN_PROGRESS', 'COMPLETED')", name='ck_idempotency_state'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('scheduled_actions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'CLAIMED', 'DONE', 'FAILED', 'CANCELLED')", name='ck_scheduled_actions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_actions_due', 'scheduled_actions', ['run_at'], unique=False, postgresql_where="status = 'PENDING'")
    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'editor', 'approver', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('whatsapp_groups',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('external_jid', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_morning', sa.Boolean(), nullable=False),
    sa.Column('default_evening', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_jid')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('display_id', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_version_at_open', sa.String(length=40), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=26), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('MORNING', 'EVENING', 'MANUAL')", name='ck_approval_kind'),
    sa.CheckConstraint("state IN ('DRAFT', 'REVIEW_PENDING', 'USER_EDITING', 'READY', 'APPROVED', 'CLOSED_NO_SHARE', 'CANCELLED', 'EXPIRED')", name='ck_approval_state'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_index('uq_approval_scheduled_once_per_day', 'approval_requests', ['kind', 'local_date'], unique=True, postgresql_where="kind IN ('MORNING', 'EVENING')")
    op.create_table('tasks',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('display_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=True),
    sa.Column('owner_id', sa.String(length=26), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_row_ref', sa.String(length=200), nullable=True),
    sa.Column('last_shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')", name='ck_tasks_priority'),
    sa.CheckConstraint("source IN ('APP', 'GOOGLE_SHEETS', 'EXCEL', 'IMPORT')", name='ck_tasks_source'),
    sa.CheckConstraint("status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'DEFERRED')", name='ck_tasks_status'),
    sa.CheckConstraint('version >= 1', name='ck_tasks_version_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_index('idx_tasks_open_due_date', 'tasks', ['due_date'], unique=False, postgresql_where="status <> 'COMPLETED' AND deleted_at IS NULL")
    op.create_index('idx_tasks_owner', 'tasks', ['owner_id'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('approval_request_id', sa.String(length=26), nullable=False),
    sa.Column('dataset_version', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('task_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_history',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('task_id', sa.String(length=26), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=False),
    sa.Column('changed_by_kind', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_task_history_version', 'task_history', ['task_id', 'version'], unique=True)
    op.create_table('share_jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('display_id', sa.String(length=20), nullable=False),
    sa.Column('approval_request_id', sa.String(length=26), nullable=False),
    sa.Column('snapshot_id', sa.String(length=26), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=26), nullable=False),
    sa.Column('scheduled_action_id', sa.String(length=26), nullable=False),
    sa.Column('action_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('deferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deferred_reason', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("deferred_reason IS NULL OR deferred_reason IN ('CROSSED_DAY_BOUNDARY', 'SNAPSHOT_STALE', 'DATA_DRIFTED')", name='ck_share_job_deferred_reason'),
    sa.CheckConstraint("state IN ('PENDING', 'SCHEDULED', 'RESCHEDULED', 'DEFERRED', 'SENDING', 'SENT', 'PARTIALLY_SENT', 'FAILED', 'CANCELLED', 'SUPERSEDED')", name='ck_share_job_state'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheduled_action_id'], ['scheduled_actions.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['report_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id'),
    sa.UniqueConstraint('scheduled_action_id')
    )
    op.create_index('uq_share_job_action_version', 'share_jobs', ['approval_request_id', 'action_version'], unique=True)
    op.create_table('share_recipients',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('share_job_id', sa.String(length=26), nullable=False),
    sa.Column('whatsapp_group_id', sa.String(length=26), nullable=False),
    sa.Column('client_message_id', sa.String(length=26), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('ack_level', sa.String(length=20), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('QUEUED', 'SENDING', 'SENT', 'FAILED', 'SKIPPED', 'CANCELLED')", name='ck_recipient_state'),
    sa.ForeignKeyConstraint(['share_job_id'], ['share_jobs.id'], ),
    sa.ForeignKeyConstraint(['whatsapp_group_id'], ['whatsapp_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_message_id')
    )
    op.create_index('uq_share_recipient_group', 'share_recipients', ['share_job_id', 'whatsapp_group_id'], unique=True)
    # ### end Alembic commands ###

    # --- Make the audit log and report snapshots genuinely immutable --------
    # scripts/setup-database.ps1 sets ALTER DEFAULT PRIVILEGES so interlock_app
    # (the application role) automatically receives SELECT/INSERT/UPDATE/DELETE
    # on every table this migration creates. That default is right for every
    # table except these two: an audit trail that the application itself can
    # edit is not a trail, and a report snapshot that can be edited after
    # approval breaks the "what you approved is what gets sent" guarantee this
    # whole system is built around. Narrowing it here, once, at the database
    # level means no future application code -- however buggy -- can UPDATE or
    # DELETE a row in either table. Only INSERT and SELECT remain possible.
    op.execute("REVOKE UPDATE, DELETE ON audit_logs FROM interlock_app")
    op.execute("REVOKE UPDATE, DELETE ON report_snapshots FROM interlock_app")


def downgrade() -> None:
    """Downgrade schema."""
    # Symmetry with the REVOKE at the end of upgrade(), though the subsequent
    # drop_table calls would make this moot on their own -- a dropped table
    # takes its grants with it. Kept explicit so downgrade() reads as the true
    # inverse of upgrade() rather than relying on that side effect.
    op.execute("GRANT UPDATE, DELETE ON report_snapshots TO interlock_app")
    op.execute("GRANT UPDATE, DELETE ON audit_logs TO interlock_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_share_recipient_group', table_name='share_recipients')
    op.drop_table('share_recipients')
    op.drop_index('uq_share_job_action_version', table_name='share_jobs')
    op.drop_table('share_jobs')
    op.drop_index('uq_task_history_version', table_name='task_history')
    op.drop_table('task_history')
    op.drop_table('report_snapshots')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_owner', table_name='tasks')
    op.drop_index('idx_tasks_open_due_date', table_name='tasks', postgresql_where="status <> 'COMPLETED' AND deleted_at IS NULL")
    op.drop_table('tasks')
    op.drop_index('uq_approval_scheduled_once_per_day', table_name='approval_requests', postgresql_where="kind IN ('MORNING', 'EVENING')")
    op.drop_table('approval_requests')
    op.drop_table('whatsapp_groups')
    op.drop_table('users')
    op.drop_index('idx_scheduled_actions_due', table_name='scheduled_actions', postgresql_where="status = 'PENDING'")
    op.drop_table('scheduled_actions')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_correlation', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
