"""sheet sync tables

Revision ID: ef1d9dacf6ad
Revises: a1e5b6f2c3d4
Create Date: 2026-09-17 17:03:37.144172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef1d9dacf6ad'
down_revision: Union[str, Sequence[str], None] = 'a1e5b6f2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_conflicts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('task_id', sa.String(length=26), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('db_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("resolution IN ('kept_db', 'kept_sheet')", name='ck_sync_conflicts_resolution'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_sync_conflicts_open', 'sync_conflicts', ['task_id'], unique=True, postgresql_where='resolution IS NULL')
    op.create_table('task_sheet_sync',
    sa.Column('task_id', sa.String(length=26), nullable=False),
    sa.Column('last_synced_version', sa.Integer(), nullable=False),
    sa.Column('last_synced_content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_known_row_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_sheet_sync')
    op.drop_index('uq_sync_conflicts_open', table_name='sync_conflicts', postgresql_where='resolution IS NULL')
    op.drop_table('sync_conflicts')
    # ### end Alembic commands ###
